### ISSUE TITLE
Make the methods in IBotTelemetryClient async

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5195]
## Issue
The OOTB implementation of BotTelemetryClient uses app insights that is pretty good at not blocking threads during IO, but if I want to log telemetry to other store (document DB for example) I will be blocking the thread.

## Proposed change
Change the methods in the IBotTelemetryClient to Task instead of void for example: 

    public interface IBotTelemetryClient
    {
        Task TrackAvailability(string name, DateTimeOffset timeStamp, TimeSpan duration, string runLocation, bool success, string message = null, IDictionary<string, string> properties = null, IDictionary<string, double> metrics = null);

        Task TrackDependency(string dependencyTypeName, string target, string dependencyName, string data, DateTimeOffset startTime, TimeSpan duration, string resultCode, bool success);

        Task TrackEvent(string eventName, IDictionary<string, string> properties = null, IDictionary<string, double> metrics = null);

        Task TrackException(Exception exception, IDictionary<string, string> properties = null, IDictionary<string, double> metrics = null);

        Task TrackTrace(string message, Severity severityLevel, IDictionary<string, string> properties);

        Task Flush();
    }

## Component Impact 
This will be a breaking change, updates will be required to BotTelemetryClient and the classes that consume it (not that many though)

## Customer Impact 
Improved performance for non app insight telemetry logging.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]
@daveta

**Comment by drub0y** [comment]
First, I want to point out that this would be a breaking API change and would violate semver rules. They also need `Async` in their suffix per existing rules of the code base. So the "proper" solution, if this is to be persued at all, would be to obsolete/hide the sync methods on the interface and add the XXXAsync versions to it.

Second, I'm not convinced this is even a good idea. Making everything `async` comes at a price and most logging/tracing implementations seen in the wild, including Application Insights, do not themselves offer async API because they buffer/batch the actual telemetry and send it asynchronously via sinks in the background. And, to be clear, the price paid is runtime overhead of async state machines and garbage collection around (potentially) allocating `Task` instances.

I would personally vote this change not be made; sync methods are already the "right" approach.

**Comment by daveta** [comment]
@scheyal : FYI, might want to triage what to do with this one..
