### ISSUE TITLE
DCR: AdaptiveCard Prompt

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-sdk#5396]
## Related

* https://github.com/microsoft/botbuilder-js/issues/882
* https://github.com/microsoft/botbuilder-dotnet/issues/614
* Several StackOverflow questions per month

## Issue

**Link to my AdaptiveCardPrompt**:

* [JS](https://github.com/mdrichardson/botbuilder-js/blob/adaptiveCardPrompt/libraries/botbuilder-dialogs/src/prompts/adaptiveCardPrompt.ts)
* [C#](https://github.com/mdrichardson/botbuilder-dotnet/blob/adaptiveCardPrompt/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AdaptiveCardPrompt.cs)

[**Samples**](https://github.com/microsoft/BotBuilder-Samples/pull/1616)

@v-kydela and I have answered quite a few questions about how to use Adaptive Cards to capture user input, particularly within Waterfall Dialogs. I think I've answered this same question 5-6 times already.

Normally, my answer is to:

1. Send the adaptive card
2. Send a blank text prompt
3. Set Activity.Text to Activity.Value in OnTurnAsync when message is a PostBack (Adaptive Card submission)

This felt hacky, so I wrote my own AdaptiveCardPrompt. 

My AdaptiveCardPrompt improves on the ActivityPrompt in the following ways:

* Card can be passed in constructor or as prompt/reprompt activity attachment 
* Includes validation for specified required input fields
* Displays custom message if user replies via text and not card input
* Ensures input is only valid if it comes from the appropriate card (not one shown previous to prompt)

## Proposed change
* Adds an AdaptiveCardPrompt class

## Component Impact 
* None

## Customer Impact 
* None

## Tracking Status
**Samples**
- [X] [Experimental Dotnet](https://github.com/microsoft/BotBuilder-Samples/pull/1616)
- [X] [Experimental JS](https://github.com/microsoft/BotBuilder-Samples/pull/1616)

**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by v-kydela** [comment]
Example of demand: https://stackoverflow.com/questions/56040323/validation-for-adaptive-cards/56047830

**Comment by mdrichardson** [comment]
https://stackoverflow.com/questions/56180596/i-am-using-bot-framework-v4-3-i-want-to-retrieve-adaptive-card-submit-values

Another one from today. Really, I'm just looking for the green light for:

1. Yes, let's make an AdaptiveCardPrompt (+ tests)
2. Let's do it the way I have it or make changes

or, 

1. No AdaptiveCardPrompt. Make ActivityPrompt non-abstract, instead

**Comment by mdrichardson** [comment]
I've seen enough demand that I'm going to continue working on this in the following order:

1. Change JS version so that notification messages aren't static --  this will allow for multilingual use-cases better
2. Implement in C#
3. Write tests for both
4. Submit PR to SDK. If they don't want it, I'll submit both to [BotBuilder Community](https://github.com/BotBuilderCommunity)

**Comment by v-kydela** [comment]
I plan to work on this too.

`AdaptiveCardPrompt` spec ideas:

1. Allow options to be specified when the prompt is constructed or when `BeginDialogAsync` is called.
1. Include an `AdaptiveCardBuilder` class that specializes in the kinds of cards that work well for `AdaptiveCardPrompt`. It could create an Adaptive Card from just a list of information that the developer wants to get from the user, kind of like FormFlow.
1. Allow the prompt to accept an Adaptive Card as a JSON string (or possibly a JSON file) or an `AdaptiveCard` object or an `AdaptiveCardBuilder` object.
1. Allow simple validation options like "require all fields" as well as highly specific validation options like a delegate for each individual field.
1. Allow reprompting options that can either modify the existing card in place to show which fields are invalid or send a new card. There should be an "auto" option that checks if the channel supports message updates.
1. Allow control over reusability of the card. If the channel supports message updates then the card could be deleted or have its button removed. Otherwise, the submit action should contain metadata that binds the card to the Adaptive Card prompt. That would mean all Adaptive Card prompts would automatically know to ignore submit actions that are from the wrong card, but if the button is clicked outside of the Adaptive Card prompt then it would be up to the developer to write code in their activity handler to ignore those actions.
1. Account for situations when the user enters text input or sends an attachment during an Adaptive Card prompt. The prompt could then make sure its card is the most recent message in the conversation by resending it and optionally deleting the old one. Because it might be ambiguous to the bot whether an activity has actually been rendered in the conversation or not, it might be a good idea to have deleting the old message and sending a new message be the default behavior, rather than updating the old message.

**Comment by mdrichardson** [comment]
Still getting issues: https://stackoverflow.com/questions/57251221/how-to-retrieve-user-entered-input-in-adaptive-card-to-the-c-sharp-code-and-how

**Comment by gabog** [comment]
I think this has been addressed [here](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/ab040141b4ba4435ceac2acfd92b26a1aaeee36e/libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPrompt.cs), closing this for now, feel free to reopen if we need it.
