### ISSUE TITLE
Skype for business Channel deprecated

### ISSUE THREAD

**Issue by andreatosato** [microsoft/botframework-sdk#5404]
Skype for business Channel deprecated.

My customer have Skype for business.
I want to do Bot framework on Teams Channel.
Can Bot framework works?

**Comment by jwiley84** [comment]
Hi @andreatosato 

Are you asking if Bot Framework is supported on the MS Teams channel? If so, yes, Teams is one of the primary supported channels for Bot Framework.  There are a couple of things to bear in mind when creating Teams bot, and the Teams team has put together a pretty thorough document on how to manage a Teams specific bot here: [Creating a Teams bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-create).

**Comment by jwiley84** [comment]
If this was not your question, please clarify and reopen this issue.

**Comment by andreatosato** [comment]
No, i must use bot framework in Skype for business.
Skype for business Channel Is deprecated...
So, i think that Teams Channel can be used in Skype for business?

**Comment by andreatosato** [comment]
[Stackoverflow](https://stackoverflow.com/questions/56331153/bot-framework-skype-for-business)

**Comment by jwiley84** [comment]
I'm not quite sure what you're looking for. Both Teams and Skype for Business (SfB) are channels for the bot framework, that is: they're just connections between your bot and communications apps that your users are using. We natively support Teams and previously supported SfB, meaning you didn't need to create your own chat client, you could simply connect to them in the Azure portal. 

With the deprecation, as of Oct 31, bots will not be able to communicate on SfB. I'm not 100% sure what this will look like on the user's end, when they attempt to communicate with a previously working bot, but that's what's planned.

A Teams bot and a SfB are the same bot. There's some special things you can add to the code of the bot, and to a Teams App Manifest, so that it can respond appropriately to Teams' various functionality such as bot menus and reactions. But they are the same bot. 

Concerning Teams migrations and interoperability:

As organizations that currently use SfB begin to migrate to Teams, admins on the SfB side can set a user's property called 'TeamsUpgradePolicy', then set the mode to 'Islands', which means a user would use both Teams and SfB concurrently. This would THEORETICALLY **possibly** allow a SfB user to communicate with a Teams user (a bot in this case).  For this to be the case, however, an organization must have already begun the migration over to Teams, which would mitigate your need to for a SfB bot in the end anyway. Also, even if this process were enacted, as of Oct 31, the bot would cease to response to any user still using SfB anyway.

[Coexistence with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence)
[Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)

**Comment by EricDahlvang** [comment]
@andreatosato Note: this is not an officially supported scenario, but it is possible to build a bot using UCWA directly.  Please have a look at https://github.com/kenakamu/UCWABot

**Comment by andreatosato** [comment]
Can I use UCWA with bot framework v4?

**Comment by EricDahlvang** [comment]
I don't know why not.  You're just using the Direct Line channel for the bot, and communicating as a user (using the ucwa apis) on sfb.

Again, note: this is not a supported scenario.  So, you're basically on your own in undocumented/uncharted territory.

**Comment by andreatosato** [comment]
Thanks Eric
