### ISSUE TITLE
[DCR] Add proxy support to the sdk

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-sdk#5469]
## Issue
Some bots are hosted in environments where a proxy is required or preferred.  While developers can specify a proxy for their own specific external calls, the framework itself also needs to be able to utilize a proxy server so that all requests, including connector services, qna maker, luis, authentication (openid metadata, etc) will be routed to the proxy server. 

The solution should be similar across sdk languages and easy to configure, with all external calls should automatically use the proxy.

## Tracking Status
**Dotnet SDK**
Add proxy support
https://github.com/microsoft/botbuilder-dotnet/issues/2281
- [ ] PR
- [ ] Merged

**Javascript SDK**
[Botframework-Connector] Proxy Settings are Ignored
https://github.com/microsoft/botbuilder-js/issues/717
- [ ] PR
- [ ] Merged

**Java SDK**
Add proxy support
https://github.com/microsoft/botbuilder-java/issues/81
- [ ] PR
- [ ] Merged

**Python SDK**
Add Proxy support
https://github.com/microsoft/botbuilder-python/issues/263
- [ ] PR
- [ ] Merged

**Docs**
Add docs explaining how to use a proxy with each of the sdk languages.
- [ ] PR
- [ ] Merged

[dcr]

**Comment by dmvtech** [comment]
Regarding .NET:

Looks like this [will be available in .NET core 3.0](https://github.com/dotnet/corefx/issues/37187) in one single spot (similar to how we can do it in [.NET Framework currently](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings)).

More info:
https://stackoverflow.com/questions/42637592/asp-net-core-defaultproxy

I think it best if we can just use proxy settings at the application level, so that we don't have to manage it otherwise. I don't know whether it's worth it to wait for 3.0 for .NET core, but it definitely would be worthwhile to ensure any httpClient/similar objects inside the SDK would use the 'globally' assigned proxies from the application level.

**Comment by cleemullins** [comment]
Unless I mis-remember, the current C# SDK (4.5.X) supports a Proxy Server.

**Comment by EricDahlvang** [comment]
It is possible to use a proxy with 4.5.x, but  the support for it could be simplified. Maybe app settings based, rather than the current code changes required.  Also, the dotnet sdk could be using HttpClientFactory with named httpclients for the places we are currently creating httpclients.

**Comment by ChupaCabre** [comment]
Hi @EricDahlvang @gabog is there proxy support for the javascript SDK at this point? If so, how are the proxy settings passed into the CloudAdapter? I've looked through the [docs](https://learn.microsoft.com/en-us/javascript/api/botbuilder/?view=botbuilder-ts-latest) & [samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples) but I don't see any mention of proxies.
