### ISSUE TITLE
Disabling buttons in Adaptive cards in Teams after user selection - C#

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-sdk#5472]
Hello Team,

Greetings for the day. We are developing Chatbot using Bot framework V4 in C#. Also we have integrated it with MS Teams. Currently we are using adaptive cards for getting inputs from user. Frequently users are trying to click the buttons in adaptive cards from old messages in bot. Is there any way to disable buttons from an adaptive card response in MS Teams after user clicked on any button in the card response. So that we shall avoid such issues. Thanks in advance for your response.

![image](https://user-images.githubusercontent.com/17233137/61691721-cb81a580-ad49-11e9-9b51-28d8719ed157.png)

Regards,
Vignesh.

**Comment by CoHealer** [comment]
@stevkan, please assist

**Comment by v-kydela** [comment]
@Vigneshramkumar - In any channel, you can have a bot [ignore old cards](https://stackoverflow.com/questions/51701003/microsoft-bot-framework-webchat-disable-adaptivecards-submit-buttons-of-previou/51774589#51774589) by having the bot remember the card by storing some metadata associated with the card. In order to distinguish between cards, you will have to inject some metadata into the submit action that's different for each card.

However, the Teams channel is special because it allows you to edit and delete messages. Do you want to leave the old cards in place so that they're still visible but without clickable buttons? Or do you want to delete the old cards from the conversation entirely?

**Comment by Vigneshramkumar** [comment]
@v-kydela - Thanks for your response. We want to have the old messages in the Teams conversation, but we need to disable the buttons in the cards (will not allow the users to click the old cards buttons again)

**Comment by EricDahlvang** [comment]
There is currently no "disabled" setting in the schema for Adaptive Card buttons. Teams does support UpdateActivity types though.

You can use UpdateActivity as part of the reply logic for the Adaptive Card, and change the previous card to exclude the buttons (replace them with text or something). This seems to be best or only way to accomplish a goal of not allowing "the users to click the old cards buttons again".

**Comment by v-kydela** [comment]
@Vigneshramkumar - Have you had a chance to try Eric's suggestion involving `UpdateActivityAsync`?

**Comment by Vigneshramkumar** [comment]
@EricDahlvang and @v-kydela  - Thanks for your suggestion. Sorry, I was not there for past two days. I will try the above one.

I will list down the actions needs to be done for removing the button in the previous adaptive card, kindly correct me if i am wrong.

1. For the first time when displaying the original adaptive card, we need to have that conversation ID and message ID to be saved.
2. Once the user clicks on that button, we need to create our new card to be displayed without that button and call UpdateActivityAsync method for updating the previous one.

For example:
Conversation ID and message ID for the displayed adaptive card is Con and Message. Then the updateActivityAsync will be as follows.
connector.Conversations.UpdateActivityAsync(Con, Message, NewCardReply).

Kindly correct me in case of any misunderstanding. 

Regards,
Vignesh.

**Comment by v-kydela** [comment]
@Vigneshramkumar - You are mostly correct, but it's actually a little easier than what you're describing.

> For the first time when displaying the original adaptive card, we need to have that conversation ID and message ID to be saved.

You need to save the ID from the resource response when you send the activity and use that as the message ID, but you don't need to save the conversation ID. Every message your bot receives from the user will contain the conversation ID you need, including the message that gets sent when the user clicks on a submit action. Refer to my latest blog post for more info: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/

> connector.Conversations.UpdateActivityAsync(Con, Message, NewCardReply)

You can actually call [`UpdateActivityAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.turncontext.updateactivityasync) through the turn context directly, and it will automatically extract the conversation ID and the activity ID from whatever you put in the activity object that you pass to it.

If you want to modify a card so that it just loses its submit actions, you'll also need to save whatever information you need to recreate the card when you're updating the activity. You might be able to get the card from the saved activity ID using a REST API call, but I like to avoid extra calls so I'm giving each of my adaptive cards a "card ID" that I can use to load that card's JSON at any time. I'm storing the card ID and the activity ID as a tuple using a state property accessor like this:

```c#
public static IStatePropertyAccessor<(string CardId, string ActivityId)> CardStateAccessor { get; internal set; }
```

When I send the activity containing the card I make sure to save the resource response ID (which is used as an activity ID) along with the card ID. **Note that in order to get a useful resource response, your activity must only contain the card attachment and the text property must be null.**

```c#
var response = await turnContext.SendActivityAsync(reply, cancellationToken);
await BotUtil.CardStateAccessor.SetAsync(turnContext, (cardId, response.Id), cancellationToken);
```

Now the tricky part is updating the activity in response to the user clicking the submit action. If you want to make sure the card's input fields don't change then you'll need to repopulate them in your updated card using the activity's value property, but that's optional. Here's some sample code that iterates through the card to create a modified card and then sends it to Teams as an update:

```c#
private async Task HandleSubmitActionAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    var activity = turnContext.Activity;

    if (activity.ChannelId == Channels.Msteams)
    {
        var savedActivity = await BotUtil.CardStateAccessor.GetAsync(turnContext, () => (null, null), cancellationToken);

        if (savedActivity.ActivityId != null )
        {
            var oldCard = BotUtil.CreateAdaptiveCard(savedActivity.CardId);
            var newCard = oldCard.DeepClone();
            var payload = JObject.FromObject(activity.Value);

            foreach (var item in oldCard.Descendants().Where(descendant => descendant.Type == JTokenType.Object))
            {
                var elementType = (string)item["type"];
                var inputId = (string)item["id"] ?? string.Empty;
                var newCardEquivalent = newCard.SelectToken(item.Path);

                // Optionally fill in the card's input values with what the user already entered
                if (elementType?.StartsWith("Input.") == true && payload.ContainsKey(inputId))
                {
                    newCardEquivalent["value"] = payload[inputId];
                }

                // Remove submit actions
                if (elementType == "Action.Submit")
                {
                    newCardEquivalent.Remove();
                }
            }

            var attachment = new Attachment()
            {
                ContentType = BotUtil.CreateContentType(activity),
                Content = newCard,
            };

            var update = activity.CreateReply(activity.Text);

            update.Attachments = new List<Attachment> { attachment };
            //update.Conversation = activity.Conversation;
            update.Id = savedActivity.ActivityId;

            await turnContext.UpdateActivityAsync(update, cancellationToken);
        }
    }
}
```

**Comment by CoHealer** [comment]
@Vigneshramkumar, resolving as closed. If this does not resolve you issue please comment .

**Comment by yuriisanin** [comment]
@CoHealer @v-kydela Looks like it's doesn't work with Telegram adaptive cards.
Here code:
`var reply = MessageFactory.Attachment(new Attachment
                {
                    ContentType = AdaptiveCard.ContentType,
                    Content = card
                });

                reply.Id = savedActivity.ActivityId;

                var response = await turnContext.UpdateActivityAsync(reply, cancellationToken);`

Method returned ResourceResponse that equal to "saveActivity.ActivityId", but nothing changed in Telegram. 
Project:
.NET Core 2.2
Bot Framework 4.6.0-preview1

**Comment by yuriisanin** [comment]
> @Vigneshramkumar, resolving as closed. If this does not resolve you issue please comment .

https://github.com/microsoft/botframework-sdk/issues/5472#issuecomment-547803337

**Comment by Annabelle7989** [comment]
Hi..this is not working ..It says the bot encountered an error..after displaying INPUT1 in cardstepasync

namespace EchoBot.Dialog
{
    public class AdaptiveDialog : ComponentDialog
    {

        public static IStatePropertyAccessor<(string CardId, string ActivityId)> CardStateAccessor { get; internal set; }


        public AdaptiveDialog(UserState userState) : base(nameof(AdaptiveDialog))
        {
            var waterfallSteps = new WaterfallStep[]
          {
                CardStepAsync,
                UpdateStepAsync
          };

            
        AddDialog(new WaterfallDialog(nameof(WaterfallDialog), waterfallSteps));
            AddDialog(new TextPrompt(nameof(TextPrompt)));
            AddDialog(new ConfirmPrompt(nameof(ConfirmPrompt)));

            InitialDialogId = nameof(WaterfallDialog);
        }
        public async Task<DialogTurnResult> CardStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
           // Display the Adaptive Card
            var cardPath = Path.Combine(".", "Resources", "LargeWeatherCard.json");
            var adaptiveCardJson = File.ReadAllText(cardPath);
            var adaptiveCardAttachment = new Microsoft.Bot.Schema.Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };
            var message = MessageFactory.Text("");
            message.Attachments = new List<Microsoft.Bot.Schema.Attachment>() { adaptiveCardAttachment };
            var response = await stepContext.Context.SendActivityAsync(message, cancellationToken);
            await stepContext.Context.SendActivityAsync($"INPUT 1");

            await CardStateAccessor.SetAsync(stepContext.Context, ("1", response.Id), cancellationToken);
            await stepContext.Context.SendActivityAsync($"INPUT 2");
            return EndOfTurn;
        }

        public async Task<DialogTurnResult> UpdateStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            var activity = stepContext.Context.Activity;
            var numberid = stepContext.Context.Activity.From.Id;
            var savedActivity = await CardStateAccessor.GetAsync(stepContext.Context, () => (null, null), cancellationToken);
            await stepContext.Context.SendActivityAsync($"INPUT");
            await stepContext.Context.SendActivityAsync(savedActivity.ActivityId);
            var cardPath = Path.Combine(".", "Resources", "RestaurantCard.json");
            var adaptiveCardJson = File.ReadAllText(cardPath);
            var adaptiveCardAttachment = new Microsoft.Bot.Schema.Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };

            var update = activity.CreateReply();


            update.Attachments = new List<Microsoft.Bot.Schema.Attachment> { adaptiveCardAttachment };
            update.Id = savedActivity.ActivityId;

            await stepContext.Context.UpdateActivityAsync(update, cancellationToken);

            return await stepContext.NextAsync();
        }
    }
}
