### ISSUE TITLE
Messages blocked by WAF OWASP rules, missing header 

### ISSUE THREAD

**Issue by gfmajchrzak** [microsoft/botframework-sdk#5497]
I need to configure the bot to be behind a WAF v2 configured to analyse the message content, apparently some headers are missing in the request from the bot connector to the API, which is capture by the WAF blocking the request, with this exceptions:

    "ruleId": "920300",
    "ruleGroup": "920-PROTOCOL-ENFORCEMENT",
    "message": "Request Missing an Accept Header",

----------------------------------------------------------------------------------    

    "ruleId": "931130",
    "ruleGroup": "931-APPLICATION-ATTACK-RFI",
    "message": "Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link",
    "Warning. Match of \"beginsWith %{request_headers.host}\" against \"TX:1\" required.",
    "data": "Matched Data: https://webchat.botframework.com/ found within TX:1: webchat.botframework.com/",
    "file": "rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf",

-----------------------------------------------------------------------------------

    "rules/REQUEST-949-BLOCKING-EVALUATION.conf",
    "Mandatory rule. Cannot be disabled. Inbound Anomaly Score Exceeded (Total Score: 7)",
    "Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomaly_score.",

**Comment by tomlm** [comment]
I don't think this is resolvable via middleware, as it's a layer below that. @Dan Driscoll

I think this is saying that requests to the bot should have Accepts header (from the channel), and calls to the channels should have the Accepts header (from the bot).

This probably impacts the connectors, and all of the channels to make sure we are compliant

**Comment by gfmajchrzak** [comment]
Agree, the thing is that i could technically change the API, but i cant change the Bot Connector call to the API since is part of the Bot Framework

**Comment by axelsrz** [comment]
Hello @gfmajchrzak, thank you for submitting the issue. We met with the WAF team about this issue and their recommendation was to move from WAF v2. to WAF 3.x.
 
The v2 is very strict and is really not design for service-to-service communication, the Accept header would be just the first of several issues that will raise.

**Comment by gfmajchrzak** [comment]
Hi @axelsrz when you say WAF 3.x you mean the Rule set 3.0? or the WAF, currentlly the customer is using WAF v2 with OWASP Ruleset 3.0

Thanks

**Comment by axelsrz** [comment]
We mean the version 3 of WAF, not just the ruleset.

**Comment by gfmajchrzak** [comment]
Hi @axelsrz, 
Sorry but i cant see any WAF v3, or find any documentation about it. Could you provide me some link?

**Comment by gfmajchrzak** [comment]
Are you referring to use WAF on Front Door?

**Comment by gfmajchrzak** [comment]
Hi Guys, I been looking an d still cant see a way to fix this without a change in the bot connector code. In my scenario, I have a WAF with multiple apps behind, the waf is a "WAF 3" which mean WAF v2 with OWASP rules 3.0. 
I cant use the exclusion list because i will open vulnerabilities on the other apps, i can disable the rule because of the same. Even if a disable this rules, new exception start to throw:

```
  "ruleId": "942400",
  "ruleGroup": "942-APPLICATION-ATTACK-SQLI",
  "message": "SQL Injection Attack",
  "details": {
    "message": "Warning. Pattern match \"(?i)\\\\b(?i:and)\\\\b\\\\s+(\\\\d{1,10}|'[^=]{1,10}')\\\\s*?[=]|\\\\b(?i:and)\\\\b\\\\s+(\\\\d{1,10}|'[^=]{1,10}')\\\\s*?[<>]|\\\\band\\\\b ?(?:\\\\d{1,10}|[\\\\'\\\"][^=]{1,10}[\\\\'\\\"]) ?[=<>]+|\\\\b(?i:and)\\\\b\\\\s+(\\\\d{1,10}|'[^=]{1,10}')\" at ARGS:text.",
    "data": "Matched Data: and 2 found within ARGS:text: 1 and 2",
    "file": "rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf",
    "line": "928"
  },

  "ruleId": "942390",
  "ruleGroup": "942-APPLICATION-ATTACK-SQLI",
  "message": "SQL Injection Attack",
  "details": {
    "message": "Warning. Pattern match \"(?i:\\\\bor\\\\b ?(?:\\\\d{1,10}|[\\\\'\\\"][^=]{1,10}[\\\\'\\\"]) ?[=<>]+|(?i:'\\\\s+x?or\\\\s+.{1,20}[+\\\\-!<>=])|\\\\b(?i:x?or)\\\\b\\\\s+(\\\\d{1,10}|'[^=]{1,10}')|\\\\b(?i:x?or)\\\\b\\\\s+(\\\\d{1,10}|'[^=]{1,10}')\\\\s*?[=<>])\" at ARGS:text.",
    "data": "Matched Data: or 2 found within ARGS:text: 1 or 2",
    "file": "rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf",
    "line": "899"
  },

```
Do we have any other implementation pattern we could use for this scenario?

**Comment by axelsrz** [comment]
Hi @gfmajchrzak, per talk with @sgellock we believe that this issue should be talked wit the WAF team, as we do not have further recommendations.

**Comment by gfmajchrzak** [comment]
Hi@axelsrz we have manage to create exclusion for false positives for SQL, but this there's 1 issue that i think needs collaboration between WAF and Bot teams:

```
ruleId": "931130",
"ruleGroup": "931-APPLICATION-ATTACK-RFI",
"message": "Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link",
"Warning. Match of \"beginsWith %{request_headers.host}\" against \"TX:1\" required.",
"data": "Matched Data: https://webchat.botframework.com/ found within TX:1: webchat.botframework.com/",
"file": "rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf",
```

**Comment by sgellock** [comment]
Hi @gfmajchrzak, my team really doesn't have experience with WAF.  We're willing to help if we can.  Given your last message, what help are you asking for?

**Comment by vijaysaimutyala** [comment]
Hi @gfmajchrzak Did you manage to resolve this issue ?

**Comment by jcbartle** [comment]
I know this issue is closed, but, just in case anyone is experiencing a similar issue and comes across this post, I wanted to share what I did to get around it. So far as I can tell, WAF v3 does not exist, so I'm not sure how anyone is supposed to follow that recommendation. As of right now, I think the below is the only workaround. Obviously the security implications need to be considered.

**Overview of Issue**

If I use OWASP 3.1, I receive several rule violations:

Request Missing an Accept Header
Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link
Mandatory rule. Cannot be disabled. Inbound Anomaly Score Exceeded (Total Score: 7)
Mandatory rule. Cannot be disabled. Inbound Anomaly Score Exceeded (Total Inbound Score: 7 - SQLI=0,XSS=0,RFI=5,LFI=0,RCE=0,PHPI=0,HTTP=0,SESS=0): Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link; individual paranoia level scores: 0, 7, 0, 0

If I use OWASP 2.2.9, I receive only one:

Request Missing an Accept Header

Either way, unless the policy is placed in detection mode only, the requests are blocked.

As a test, I placed my default policy in detection mode and created a second policy to test OWASP 3.2. I receive the following rule violations in that configuration:

Request Missing an Accept Header
Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link
Inbound Anomaly Score Exceeded (Total Score: 7)

**Workaround**

In order to get around this, you have to go into the _Managed Rules_ section of your policy, and disable the individual rules for _Request Missing and Accept Header_ and _Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link_. After doing that and saving the configuration, my bot is able to function normally, and I no longer get the Inbound Anomaly Score Exceeded entries in the log.
