### ISSUE TITLE
Generate architecture maps/poster(s) of the Bot Framework for CSS

### ISSUE THREAD

**Issue by sgellock** [microsoft/botframework-sdk#5502]
To aid CSS in understanding the parts for the Framework, we need to produce one or more architecture maps that outline the architecture of the framework

**Comment by sgellock** [comment]
We're starting the work on this in R7.  We are not tracking to have enough of these done for public consumption until R8.

**Comment by cleemullins** [comment]
@Zerryth Can you update this bug with current status and links? Let's get this pushed across the finish line!

**Comment by Zerryth** [comment]
Hmm...need to finagle with my GitHub notification settings, 'cause I haven't been able to get notifications on any activity since getting back--grrr! Apologies for the delayed update, now that I'm seeing your comment:
___
Links:
1. [ActivityFlow](https://github.com/Zerryth/Mermaid/tree/master/MarkdownFiles/ActivityFlow)
2. [Authentication](https://github.com/Zerryth/Mermaid/tree/master/MarkdownFiles/Authentication)
3. [Skills](https://github.com/Zerryth/Mermaid/tree/master/MarkdownFiles/Skills)
___
Status:
1. ActivityFlow - have 3 that design (Marc) will help turn into more visually appealing graphics. In total for done diagrams in this section, narrowed it with the help of John/Steven/Carlos to 1 generalized, 3 BF protocol, 1 block diagram of ActivityFlow 
2. Authentication - confirmed content correctness with Carlos, and I have cleanup feedback that I still need to do, which I'll get to after submitting PR for [bb-js#1663](https://github.com/microsoft/botbuilder-js/issues/1663)
3. Skills I had trudged through painstakingly in January, and was working towards diagramming OAuth in Skills, but stopped when I found issues with the [connectors and oauth scoping](https://github.com/microsoft/botbuilder-dotnet/issues/3386), since there were going to be changes made. Jonathan Fingold from docs liked the sketched out diagrams of the skills concepts that are in this section and would've liked them for R8, however I don't think Marc will be able to get to these before the deadline, given that he's working on Activity Flow

___
I think, once cleaned up, they'll actually suitable to go into the botframework repo, without Marc's magic touch, in the UML Diagrams section, to let the knowledge be out there--don't know if you guys would prefer to embed them into docs or not

**Comment by Zerryth** [comment]
Update: 
1. I have a [draft PR](https://github.com/microsoft/botframework-sdk/pull/5771) with the updated diagrams to enter them into botframework-sdk repo. Holding the PR until Marc gets some of the more visually-appealing graphics completed, however if there's a demand to get them in faster, we have the option of merging them sooner with the Mermaid-only diagrams
2. Upated the [root of my personal repo](https://github.com/Zerryth/Mermaid), so you can actually see the diagrams right away without cloning to have more of a Table of Contents format to ease navigation

___

Guidance: per John, Dr. Gum, and briefly Axel and Chris in 1st diagram review meeting, I've created more [class diagrams to illustrate the complex architectural structure](https://github.com/Zerryth/Mermaid/blob/master/Authentication/README.md#architecture-of-authentication-in-bot-framework) of our `OAuth` system.

Those are only the classes that the `OAuthPrompt` touches. I do _not_ have diagrams created for the auth bits that are for *Channel to Bot* realm, if they don't appear in `OAuthPrompt`. 

Question is: **is it worth it to also do class diagrams and sequence diagrams for the Channel to Bot auth flow?**

'cause what's missing are like...JwtTokenValidation classes, the token request via getToken off the AppCredentials directly (instead of off the BotFrameworkAdapter), etc.

Or should I stop working toward more diagrams and prioritizing getting my other [coding bug done with making a validation layer for streaming](https://github.com/microsoft/botbuilder-js/issues/1445)?

___

@cleemullins @stevengum @axelsrz @carlosscastro @johnataylor - dunno if any of you have an opnion/guidance?

**Comment by Zerryth** [comment]
per steven, going to go ahead and make Channel to Bot auth diagrams as well

**Comment by Zerryth** [comment]
Update from Monica:
- **Work on this is paused**, due to lack of Design bandwidth to turn diagrams into beautiful graphics
- Completed [Channel-to-Bot auth diagrams](https://github.com/Zerryth/Mermaid/blob/master/Authentication/ChannelToBot/README.md). Review needed to verify the ABS bits that's blackbox to me--the diagrams were made based off of well-known OAuth 2.0 & OpenID Connect patterns though
