### ISSUE TITLE
Dedicated documentation for every language and SDK

### ISSUE THREAD

**Issue by vyomanaut** [microsoft/botframework-sdk#5643]
Documentation is a very important for a developer especially when the community is relatively small. Its a real pain when you are searching for something particular and in the search results i see results for languages i am not using as well as for a SDK i am not using . 

SDK v4 needs to have its own separate documentation and not be clubbed with v3 documentation , leads to redundant search terms , same for the various supported languages.

**Comment by v-kydela** [comment]
Hello @vyomanaut - Thank you for the post!

You are absolutely right that documentation is very important for developers. However, the v4 Bot Builder SDK has been designed with parity in mind, so if something can be done in one language it can almost always be done the same way in the other three languages. This should help when you're searching for answers and you find posts that use a language you're not using.

The v4 SDK actually does have its own documentation that's separate from the v3 documentation. You can see that here:

- [Azure Bot Service v3 docs](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-3.0)
- [Azure Bot Service v4 docs](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0)

V3 has separate documents for .NET and Node because the features/functionality were different between them. V4 has more parity and so the different languages share the same documents and just use language selection tabs in certain portions of the documents. Python and Java will likely be added to the documentation soon.

We are constantly improving the documentation and we appreciate your feedback. If you have any specific concerns about specific things that you can't find in the documentation, please ask a question in the appropriate place as seen [here](https://github.com/microsoft/botframework-sdk#questions-and-help) and my team will see it.

**Comment by vyomanaut** [comment]
Completely Understand . 
Thank you !
