### ISSUE TITLE
Unable to authenticate through bot without magic code - Bot Framework V4

### ISSUE THREAD

**Issue by VidishaPasupuleti** [microsoft/botframework-sdk#5676]
On launch of the bot, it is prompting for authentication with a sign in card when using Oauth prompt in bot framework V4. Once the user clicks on sign in button, a magic code is being generated and the user is able to login only upon entering the magic code. Need a way to authenticate without generating the magic code.

**Comment by v-kydela** [comment]
Hi @VidishaPasupuleti - you are describing channel-specific behavior. What channel are you using?

**Comment by VidishaPasupuleti** [comment]
I am using directline.

**Comment by VidishaPasupuleti** [comment]
@v-kydela I am using directline

**Comment by VidishaPasupuleti** [comment]
Hi @v-kydela I am using directline

**Comment by v-kydela** [comment]
@VidishaPasupuleti - Okay, but are you using Web Chat or your own custom Direct Line client?

**Comment by benbrown** [comment]
@VidishaPasupuleti We need an answer to the question above to get to the bottom of this. Can you follow-up?

**Comment by VidishaPasupuleti** [comment]
@v-kydela @benbrown  We are using Webchat.

**Comment by v-kydela** [comment]
@VidishaPasupuleti - There are some potential solutions outlined in this thread: https://github.com/Microsoft/BotFramework-WebChat/issues/1238

1. [Have you tried using a Direct Line token instead of a Direct Line secret?](https://github.com/microsoft/BotFramework-WebChat/issues/1238#issuecomment-433310068)
2. [Is the user's browser set to block 3rd party cookies?](https://github.com/microsoft/BotFramework-WebChat/issues/1238#issuecomment-433480872)
3. [Have you tried enabling enhanced authentication options in the Azure portal?](https://github.com/microsoft/BotFramework-WebChat/issues/1238#issuecomment-486907126)

**Comment by v-kydela** [comment]
@VidishaPasupuleti - Are you still working on this?

**Comment by VidishaPasupuleti** [comment]
@v-kydela Hi, I am working on it. I will try out the links that you have shared. 
Thanks.

**Comment by anusharavindrar** [comment]
@VidishaPasupuleti are you still working on this? Is your issue resolved?

**Comment by anusharavindrar** [comment]
Closing the issue due to no response. Feel free to reopen if you have need to get this resolved.
