### ISSUE TITLE
CodeActions should more accurately model waterfall steps 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5752]
## Issue
While `CodeActions` look similar to waterfall steps there are some differences which prevent directly porting a waterfall step to a code action. Here are the key differences:
- To skip to the next step in a waterfall you call `step.next()` but for a code action you have to call `dc.endDialog()`.
- To end a waterfall dialog you call `dc.endDialog()` but to end a code actions dialog you have to call `dc.parent.endDialog()`.
- The `WaterfallStepContext` has a `values` property which holds temp variables for the waterfall. This has been replaced with the `DialogStateManager` in adaptive. 
- The `WaterfallStepContext` has a `results` property which lets you access the results returned by the dialog called from the previous step.  This concept doesn't really exist with code actions as each action is expected to read & write its own values to memory.   

## Proposed change
We should update the context object passed to a code actions handler to be model  the step context passed to existing waterfall steps. This will simplify porting of waterfall steps to code actions and more importantly, maintain a waterfall developers expectations for how steps should work. 

I propose creating a new `CodeActionContext` object that derives from `SequenceContext` and has the following methods/behaviors:
- The `CodeActionContext` will extend the parent adaptive dialogs `SequenceContext`. This means that calling `cac.endDialog()` or `cac.replaceDialog()` will work against the actions current dialog, just like in waterfalls.
- A `CodeActionContext.next()` method will navigate to the next action by internally calling `endDialog()` on the code action.
- A `CodeActionContext.values` property accessor will call `DialogStateManager.getValue('dialog')` to return the dialogs scratch memory space. This mapping will simplify the porting existing waterfall steps to code actions without modification.
- While we could add a `CodeActionContext.results` property that internally maps to `turn.lastResult` I propose we leave this off as this represents the main conceptual shift from waterfall steps to code actions. Any porting errors that come up from this will help ensure that devs are working with adaptive dialogs properly.
  
## Customer Impact 
This would be a breaking change to any bots that are currently using `CodeActions`.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by vishwacsena** [comment]
@Stevenic I like this proposal except for two pieces of feedback - 
1. `cac.next()` - is this required? I understand for parity but do we need to use this? Said alternatively what happens if a code action does not return anything or does not call cac.next()? As much as we keep familiarity to waterfall, I would not want this to feel out of place for someone that is coming straight to adaptive. I prefer to support cac.next() but have samples for adaptive showcase use of dc.endDialog
2. `cac.endDialog()`, `cac.replaceDialog()` - this feels confusing to me. By definition, we are saying every single action is a dialog. So end and replace should apply to the code action itself. I understand the need to change this behavior to match waterfall dialogs but I worry that we will be doing it at the cost of special casing code actions to developers that are **not familiar** with waterfall. I prefer `cac.parent.endDialog()` - its not much different from what we have in waterfall anyways and re-iterates one of the strengths of adaptive.

**Comment by vishwacsena** [comment]
Closing this per triage. We will investigate this if other customers run into this issue.
