### ISSUE TITLE
Incorrect Chinese text render on Dialog

### ISSUE THREAD

**Issue by baole** [microsoft/botframework-sdk#5782]
**Describe the bug**

Our bot uses dialog to ask users to fill data. Chinese text doesn't properly show whereas English text renders correctly. The same Chinese text is rendering correctly on message as well.

Please see below attachment for details:
![image](https://user-images.githubusercontent.com/1460168/76589993-3a378d00-64ec-11ea-858e-f38073e9dc07.png)

![image](https://user-images.githubusercontent.com/1460168/76590006-43c0f500-64ec-11ea-91f2-b926e00afa3a.png)

I'm using REST API V3.
I tested on Mac OS/Chrome browser, Mac OS/Native app.

Any help?

(the issue was originally posted here https://github.com/MicrosoftDocs/bot-docs/issues/1599)

**Comment by v-kydela** [comment]
@baole - It's unclear what you're doing differently to trigger the behavior in these two screenshots. When you say "Our bot uses dialog to ask users to fill data" do you mean to say that the second screenshot is a task module?

I can see that you're using different data in these two cases. I suppose it's possible that your the JSON could be encoded differently but I suspect it's just a Teams bug. There are a few things we need you to do in order to help diagnose the cause of this issue:

1. Please take the Adaptive Card from the task module and try sending that exact same card as a normal message outside of the task module. This will determine if the task module is indeed the problem.
2. Please post that Adaptive Card so we can try to reproduce the problem on our end.
3. Since your Teams client appears to be using English, please try setting your app language to Chinese and see if that makes a difference.

**Comment by baole** [comment]
@v-kydela Thanks. We are using task module. I just figured out that it's our issue. Indeed, when a user clicks on "Open dialog" (in the first screenshot), the bot return a "task/fetch" payload to show a popup form. The `contentType` of this response should be explicitly defined as "application/json" or it doesn't work.

Anyway, thank you for your suggestions.
