### ISSUE TITLE
How to edit the start time of video in video card?

### ISSUE THREAD

**Issue by Mrinnaal** [microsoft/botframework-sdk#5783]
I want to start my video from a specific time in my video card. Is there any way I could do it? Please let me know.....

**Comment by v-kydela** [comment]
@Mrinnaal - While the SDK repo is only for DCR's, I will see if I can help anyway.

The [Bot Framework video card schema](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference#videocard-object) contains no "start time" option. It's conceivable that a specific channel could provide such an option, but you would have to check the API of the channel you're using to see. If you are building your own Direct Line client then you can play videos however you want. Otherwise, the best option is probably to just edit the video so that it starts where you want it to.

Does this resolve your issue, and would you be willing to provide feedback about the experience you had posting on GitHub?

**Comment by CezaryMarcjan** [comment]
For product behavior, how-to, or general understanding questions, please use Stackoverflow. 

https://stackoverflow.com/search?q=bot+framework
