### ISSUE TITLE
bot returning welcome message again when i click on button

### ISSUE THREAD

**Issue by kksantosh** [microsoft/botframework-sdk#5801]
```node
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const { CardFactory, ActionTypes, ActivityHandler, MessageFactory } = require('botbuilder');
const { DialogBot } = require('./dialogBot');
var BotResponses = require('../constant/string');
var ConstantVariables = require('../constant/constantValue');

class DialogAndWelcomeBot extends DialogBot {
    constructor(conversationState, userState, dialog) {
        super(conversationState, userState, dialog);

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; cnt++) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity(BotResponses.GREET);
                    await context.sendActivity(BotResponses.GREET1);
                    const buttons = [
                        { type: ActionTypes.ImBack, title: ConstantVariables.SELF_ASSESSMENT, value: ConstantVariables.SELF_ASSESSMENT },
                        { type: ActionTypes.ImBack, title: ConstantVariables.sympton, value: ConstantVariables.sympton }
                    ];
                    const card = CardFactory.heroCard('', undefined,
                        buttons, { text: 'Please select one of the categories below or type in your question.' });

                    await context.sendActivity({ attachments: [card] });
                    // await dialog.run(context, conversationState.createProperty('DialogState'));
                }
            }

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
}

module.exports.DialogAndWelcomeBot = DialogAndWelcomeBot;
```

**Comment by v-kydela** [comment]
Hello @kksantosh 

This repo is only for design change requests. We display a message when you create an issue here that includes the following:

> ## This is not for asking questions or filing bugs
> 
> To get help with an issue with your bot
> * ["How To"](https://stackoverflow.com/help/how-to-ask) questions should be submitted on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework).

My team sees every question that uses the `botframework` tag. I'll be happy to help you if you post a question on Stack Overflow, but make sure you read the [how-to-ask](https://stackoverflow.com/help/how-to-ask) help document so that you can include enough relevant information for people to know how to help you. It will be particularly important to mention which channel you're using, and it will be even more helpful to post screenshots of the behavior you're seeing in the channel.

I'm closing this issue now.

**Comment by kksantosh** [comment]
I have just submitted issue on Stack Overflow . please once look in that.

**Comment by v-kydela** [comment]
I saw it here: https://stackoverflow.com/questions/61115151/bot-returning-same-welcome-message-again-when-i-click-on-button
