### ISSUE TITLE
Telagram Webhook not send preCheckoutQuery to my bot

### ISSUE THREAD

**Issue by 4ININ** [microsoft/botframework-sdk#5828]
I trying get preCheckoutQuery from telegram webhook
After configure webhook https://dev.botframework.com/ was set correctly like 
`{"ok":true,"result":{"url":"https://telegram.botframework.com/api/telegram/my-bot/secret","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}`
My endpoint myhost/api/messages
After this steps my bot handle messages correctly, but preCheckoutQuery from sendInvoice does not sended on my bot

**Comment by v-kydela** [comment]
Hello @4ININ 

It looks like you're trying to use the Telegram API with Azure Bot Service endpoints. If you're using the ABS Telegram channel connector then you'll need to use the Bot Framework API instead, and there's a good chance `preCheckoutQuery` is not supported. If you believe this to be a problem with the Telegram connector, you could post this issue in the [services repo](https://github.com/microsoft/BotFramework-Services). The SDK repo is only for design change requests.

If you'd still like to get help here, you will need to give more information. Show your code, explain what you're trying to accomplish, provide repro steps, explain your expected behavior, provide screenshots, and link to any documentation you've followed so far.

**Comment by 4ININ** [comment]
@v-kydela Thank you for advice! 
In this case, I will try to draw up my sequence of actions in detail and let you know everything you need.

**Comment by v-kydela** [comment]
@4ININ - You might also consider posting on [Stack Overflow](https://stackoverflow.com/) if you'd like to reach a wider audience

**Comment by v-kydela** [comment]
@4ININ - Are you still working on this?

**Comment by 4ININ** [comment]
> @4ININ - Are you still working on this?
@v-kydela yes

**Comment by 4ININ** [comment]
@v-kydela done, please check my example project
https://github.com/4ININ/telegramWebhookPreCheckoutQueryIssue.git

**Comment by v-kydela** [comment]
@4ININ - I've just received confirmation that the Azure Bot Service does not support the Telegram payment system. If you want access to all Telegram events, you'll have to connect your bot to Telegram on your own.

I can see that you're already bypassing ABS for most of your API calls. Your bot is highly unusual in that it sends messages to the Telegram API directly instead of using the turn context, etc. It probably shouldn't be too hard for you to separate your bot from ABS completely.

Is there anything else you need with regard to this issue?

**Comment by 4ININ** [comment]
@v-kydela Im not sure about your ansver. 

Check this diagram [Payment diagram process](https://raw.githubusercontent.com/4ININ/telegramWebhookPreCheckoutQueryIssue/master/TranzzoPaymentDiagram.png)

Becouse preCheckoutQuery is one of the optional parameter of Update object:
https://core.telegram.org/bots/api#update
As you can see, the Update object can also return message field, inline_query field etc.
There must be a way to get Update object via webhook. I am almost completely sure that is a problem with the Telegram connector

**Comment by v-kydela** [comment]
@4ININ - That's what I said. The Telegram connector is part of the Azure Bot Service, and it does not support `preCheckoutQuery`. I don't think there's anything you can do to fix your problem while you continue to use the Telegram connector.

**Comment by v-kydela** [comment]
@4ININ - I'm going to close this issue now. Please feel free to reach out again if there's anything else you need help with.
