### ISSUE TITLE
I can connect the dialogflow to botframework by nodejs

### ISSUE THREAD

**Issue by DaiLocIU** [microsoft/botframework-sdk#5834]
## This is not for asking questions or filing bugs
i don't know...

**Comment by jwiley84** [comment]
There is very little in this question to go on. Do you  mean Google's DialogFlow? Do you mean creating a bot using the Bot Framework Composer? 

I'm going to close  this issue, because the Bot Framework team prefers that **how-to** questions be asked on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework). The botframework-sdk is for feature tracking only. If your question is concerning connecting a botframework bot with google's dialogflow, please ask on stack overflow. If it's concerning a bug with composer, please ask on the composer repo.
