### ISSUE TITLE
InvokeResponse should be part of Bot.Schema and not Bot.Builder

### ISSUE THREAD

**Issue by RamjotSingh** [microsoft/botframework-sdk#5841]
InvokeResponse is not dependent on the Adapter layer and should be moved to Bot.Schema

**Comment by cleemullins** [comment]
Let's figure out what's happening here before making any code changes.

**Comment by EricDahlvang** [comment]
In javascript, this interface was initially in botbuilder, but moved to botbuilder-core with this PR: https://github.com/microsoft/botbuilder-js/pull/1771/files#diff-275e2bdf0fa067a921f9d674b6ded3df

In dotnet, this class has been in Microsoft.Bot.Builder since it was added with this PR: https://github.com/microsoft/botbuilder-dotnet/commit/39e1726c6f307f1a257384a529438e666e5fb41c#diff-e436b7655024dfa521d510eb657c3090

It does seem like it should be in botbuilder-schema, but it would be a breaking change to move it at this point.

**Comment by cleemullins** [comment]
Thanks Eric. Given that, we can close this out.
