### ISSUE TITLE
Issue in bot framework .NET execution from linux server 

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-sdk#5876]
Hello All,
I am using bot channel registration in azure and deployed by .NET core project in a linux server. The code was working fine in Mac environment after build. But when deploying and running in linux server, the POST call from azure is not getting triggered. We are using NGINX as reverse proxy for forwarding the azure requests to the bot application. But we are getting 400 error for POST when trying to trigger the endpoint api/messages from azure.
PFB the NGINX setting we have configured, error log in nginx.

![image](https://user-images.githubusercontent.com/17233137/84065465-0c29f200-a9e2-11ea-9995-6b732c722b1d.png)

Error log:

![image](https://user-images.githubusercontent.com/17233137/84065615-46938f00-a9e2-11ea-9068-337e8d134ab8.png)

I have done the azure bot service correctly by providing the endpoint. Also there is no issue in azure set up since it is working fine when using NGROK based endpoint by running the bot in Mac on same port 5000 as used in linux. Kindly help in solving the issue. Thanks in advance.

**Comment by mdrichardson** [comment]
@Vigneshramkumar Is your bot running on port 5000? From within the Linux container, please run `sudo lsof -i -P -n | grep LISTEN` and copy/paste the output here. If you follow my guide from your previous question, you shouldn't need to do anything specific with nginx.

**Comment by mdrichardson** [comment]
@Vigneshramkumar 

* Please [configure error logging at the `info` level for nginx](http://nginx.org/en/docs/ngx_core_module.html#error_log) so that we can dig into this more. 
* I also thing there may be an issue listening on both 80 and 443. I believe you need to list them separately to avoid SSL errors, but it's been awhile since I did anything with nginx
* [It may also have to do with your Upgrade header](https://github.com/dotnet/aspnetcore/issues/17081#issuecomment-553741407)

This isn't a common way of hosting the bot, so it's going to be all trial and error from here. I'm happy to continue trying to help, but this appears to be more of an nginx issue than a bot issue, assuming that the bot works locally and also when deployed using a recommended method.

**Comment by Vigneshramkumar** [comment]
@mdrichardson - Issue is resolved after configuring nginx with the following proxy headers.

proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto $scheme;

Thanks for your support.
