### ISSUE TITLE
ContextOnly is missing in Microsoft.Bot.Builder.Dialogs response.Answers

### ISSUE THREAD

**Issue by domacKA** [microsoft/botframework-sdk#5935]
##ContextOnly is missing in Microsoft.Bot.Builder.Dialogs response.Answers

In JSON the tag "isContextOnly" is present (found in [https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/multiturn-conversation](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/multiturn-conversation#a-json-response-to-return-an-initial-answer-and-follow-up-prompts))

But with c# using Microsoft.Bot.Builder.Dialogs there is no way to get for example response.Answers[0].isContextOnly

![Content-Only2](https://user-images.githubusercontent.com/65910471/85126259-6bcb9d00-b22d-11ea-9265-01e2e72c03e4.jpg)

[stackoverflow.com](https://stackoverflow.com/questions/62468841/how-is-it-possible-to-get-the-iscontextonly-tag-from-microsoft-qna-maker-for-m)

**Comment by domacKA** [comment]
@jwiley84 Great, thank you.

**Comment by jwiley84** [comment]
@domacKA 

I've found your question on Stack Overflow [here](https://stackoverflow.com/questions/62468841/how-is-it-possible-to-get-the-iscontextonly-tag-from-microsoft-qna-maker-for-m), as well as the sample that handles context only. I'm going to close this issue, as the Bot Framework team prefers that this repo is limited to DCRs and major bugs  in the SDK. I'll work with you over on Stack Overflow, and if it turns out that this is a bug, we'll reopen the issue in the proper repo.
