### ISSUE TITLE
Allow for quick responses bypassing middleware (equiv to V3). BotFrameworkAdapter processActivity is returning an HTTP response only after middlewares and activity processing.

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-sdk#6005]
Capturing multiple customer & 1P feature requests.

This is a feature request, which comes up a lot.  This would be a javascript answer for:  See related issue #5665.  (and other issues, primarily related to 15 second timeouts …. something many bots run into)

See also: https://github.com/microsoft/botframework-sdk/issues/5665#issuecomment-670805310 ).

**Comment by cleemullins** [comment]
Why would the described behavior be wrong? 

It seems that we want the Adapter to return an HTTP response after middleware and Activity Processing are done. A Middleware can choose to prevent other middleware from running and directly return an answer. 

Could you elaborate on what's needed and why? I think sufficient flexibility in the system is already present to get the desired result.

**Comment by cleemullins** [comment]
@joshgummersall Can you take a look at this with fresh eyes, perhaps sync w/ @stevengum, and see if we can do something here to help the customers with their ask?

**Comment by scheyal** [comment]
(Marked as R11 for visibility)

**Comment by cleemullins** [comment]
@EricDahlvang I don't think this will fit in R11, but we can prioritize for R12. Can you put together a design for this so that we can tackle in R12?

**Comment by Stevenic** [comment]
Adding my proposal for this feature from back in 2018

microsoft/botbuilder-dotnet#598

**Comment by Stevenic** [comment]
I've explored doing this with middleware in the past but there are 2 things that make doing this with middleware difficult:

1.  You would need to be able to both continue execution of the middleware pipe and return immediately which is impossible.
2.  Even if you could somehow fork the thread to achieve #1 you would need to replace the TurnContext with a clone given that it's disposed of once the middleware pipe completes. Again, that's not currently possible.

The one possible way to achieve this via middleware would be to start a new proactive conversation within your middleware handler but that's tricky because a) you don't have easy access to the bots logic and b) you'd need to add logic to cause your middleware to pass through the proactive call otherwise you'll go into an infinite loop.

The cleanest way to do this is at the adapter level via a new option.  This should be opt-in behavior for numerous reasons:

*   If you're running in a shared hosting environment you'll be outside the scope of a request so you're at risk for your compute node to be recycled mid request.
*   By default, your bots state won't be persisted until after the completion of the turn which could be seconds or minutes later. This opens you up to a greater chance of concurrency issues with regards to state. 
*   The ABS service will no longer be able to log failures that occur in the handling of requests sent to your bot. I view that as low impact but worth noting

With that said, if your bot needs to perform long running queries it's currently a pain to implement support for this in v4 and impossible for composer users without jumping through even more hoops.  Adding this as an optional feature would greatly simplify the handling of long running requests. Here are some implementation recommendations I'd suggest:

*    `invoke` activities will need to be special cased as will `expectReplies` mode for skill invocations. These need to be passed through as normal.
*   I'd strongly recommend you pair this option with the `TypingMiddleware` as this will convey to the user that the bot is busy and minimize the chance of concurrency issues.
*   We could consider adding actions to better let the developer manage their bots state. Via these actions the developer could save their bots state prior to performing a long running operation and then re-load it once the operation completes. That will further minimize the chance of concurrency issues.
