### ISSUE TITLE
Request for The Ability to Proactively Create Group Conversations in MS Teams

### ISSUE THREAD

**Issue by Debro012** [microsoft/botframework-sdk#6064]
## This is not for asking questions or filing bugs

To get help with an issue with your bot
* ["How To"](https://stackoverflow.com/help/how-to-ask) questions should be submitted on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework).

To file an issue against a component please go to the components repo
* [Create Azure Bot Framework Service or Channel issue](https://github.com/Microsoft/botframework-services/issues/new/choose)
* [Create Bot Builder Tools issue](https://github.com/Microsoft/botbuilder-tools/issues/new/choose)
* [Create Bot Builder SDK V3 (.NET or Javascript) issue](https://github.com/Microsoft/botbuilder-V3/issues/new/choose)
* [Create Bot Builder SDK V4 .NET issue](https://github.com/Microsoft/botbuilder-dotnet/issues/new/choose)
* [Create Bot Builder SDK V4 Javascript issue](https://github.com/Microsoft/botbuilder-js/issues/new/choose)
* [Create Bot Builder SDK V4 Java issue](https://github.com/Microsoft/botbuilder-java/issues/new/choose)
* [Create Bot Builder SDK V4 Python issue](https://github.com/Microsoft/botbuilder-python/issues/new/choose)

## Issue

The Bot Framework provides an ability for creating 1:1 conversations and proactively messaging a user. However, it does not seem possible to create a group conversation via the Bot Framework, add the Bot, and proactively message the group members.

## Proposed change

It would be great if The Bot Framework provided an ability for group conversations to be created proactively via the Bot--rather than a Bot only being allowed to be added to an existing conversation. A good use case would be for a Bot which needs to proactively create a group conversation in Teams and add members from an application support group to triage an issue.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by Debro012** [comment]
#5661

**Comment by sgellock** [comment]
@clearab, can you drive this one?

**Comment by clearab** [comment]
Hello - Thank you for reaching out with this request. This is something that I know the Teams group has considered in the past, but has so far declined to support due to (I believe) privacy and spam concerns. If you'd like to see it reconsidered the best path forward would be to create and vote for the feature on their UserVoice board here: https://microsoftteams.uservoice.com/forums/555103-public?category_id=194614

If you'd like to engage with them directly, they outline the methods here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback

Adding @tacri (from the Teams group) for visibility - please correct me if any of the above is incorrect!
