### ISSUE TITLE
Unable to save Facebook channel registration pageID & token

### ISSUE THREAD

**Issue by lqchinh88** [microsoft/botframework-sdk#6127]
## Version
Botframework v4

## Describe the bug
I'm setting up Facebook channel registration for my bot. I have multiple Page IDs and Page Access Tokens that's working fine. However, there's one pair of Page IDs - Page Access Token that always generate "Unable to save". I got this message when trying to save using CLI : "Facebook API error ID: |d2f0db60-4f7d774518f4fc7d." 

## To Reproduce
Go to "Bot Channels Registration"
-> Channels
-> Facebook
Input Page ID 2067835403503665 ,  I cant include the token herefor security reason.
My subscription ID is : 3fbc0dbe-5d91-4e57-8037-9552dcd7a596

## Expected behavior
Should be able to save channel registrations with given pair of IDs and Token

**Comment by jwiley84** [comment]
Can you clarify your case here? Which CLI are you using and the full command (with tokens and IDs redacted)?

**Comment by lqchinh88** [comment]
az bot facebook create -n Kratos-Production -g innaway-cuong-bot --appid 381957805749898 --page-id {pageID} --secret {secret} --token {token}

**Comment by hcyang** [comment]
Hi @jwiley84, please update regarding to @lqchinh88's response. Thanks.

**Comment by lqchinh88** [comment]
Any update ?

**Comment by lqchinh88** [comment]
I'm pretty sure the token is valid with all needed permission, is there any way I can add them into channel settings without verification, just to get it to work first ? It's a production environment so I dont have much time

**Comment by lqchinh88** [comment]
I found the issue. One of the existing token expired, so I was unable to save new one when it's still in the list.
If there's a feature highlighting only the unacceptable one , and accept the rest, we will be able to manage our page IDs and tokens easier

**Comment by stevkan** [comment]
@lqchinh88, apologies for the delayed response. Unfortunately, the one who was helping you took ill. I am glad you were able to discover what the issue was. As for the channel indicating invalid tokens, that would be a 'feature request'. If you feel strongly about this, you can post this request at the [BotFramework-Services](https://github.com/microsoft/BotFramework-Services/issues/new) repo for consideration by the Services team.

In the mean time, I am going to close this issue as resolved.
