### ISSUE TITLE
Outgoing WebHook Activity.ChannelData has invalid teamsTeamId

### ISSUE THREAD

**Issue by dviry** [microsoft/botframework-sdk#6145]
According to the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#teams-channel-data) and my understanding the received Activity.ChannelData should include the teamsTeamId - yet even the [Example below](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#example-channeldata-object-channelcreated-event) seems to show an invalid teamId (note that it's exactly the same value as channelId). 

I am experiencing the same issue when receiving such WebHook callbacks.

That value is not accepted as a valid Teams GroupId - or is my understanding of the value's meaning wrong? 
If so, how can I get the actual GroupId of the Channel (required for [all Channel GraphApi calls](https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&tabs=http))? It's nowhere to be found in the received Activity...

Thanks in advance

**Comment by EricDahlvang** [comment]
Sorry, but it looks like channelData.teamsTeamId is **Deprecated**.   I'm not sure how long it has been deprecated, but it is possible the value is no longer sent by Teams.

Is the goal to retrieve a list of channels in a Team?  We have some documentation describing how to accomplish this in a bot here:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#get-the-list-of-channels-in-a-team

Please describe in more detail the requirements. 


Regarding the documentation: please open an issue on the page with the Feedback tool in order to provide recommendations for improvements:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#next-steps

**Comment by dviry** [comment]
The linked example shows the "supported" channelData.Team.Id which has the same (wrong) value.
The docs are not wrong - I am receiving the same "false" information.
I cannot use the example you linked since I am using "outgoing webhook bot" as mentioned in my issue Ticket.

I would kindly suggest you read again my first message since none of your answers seem to reflect my mentioned issue - How to get the teamId from the activity sent by "outgoing webhook"?

Thanks in advance

**Comment by EricDahlvang** [comment]
I apologize if I'm not understanding.  I'm only familiar with the Bot Framework and SDK.  Teams webhooks are outside of my area of knowledge.  Stack overflow might be a better place for this question.  This is the BotFramework-SDK repository, and is intended to be used for DCR's related specifically to the Bot Framework and SDKs.

Does this stack overflow answer help? 
https://stackoverflow.com/questions/63012792/sending-an-ms-teams-message-using-the-microsoft-graph-api-or-bot-api

**Comment by clearab** [comment]
Hi - The channelData.teams.id field is the conversationId of the default (typically general) channel of for that team. It is not the same as the groupId. To get the Id needed for Graph calls use the [getTeamDetails](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=json#get-teams-details) method.

**Comment by dviry** [comment]
I guess the name is misleading - either way, I cannot query the bot's serviceUrl since I do not have a token for it (not running within a Bot context - it is an "[outgoing webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook)"). The GraphAPI equivalent requires a TeamsID+ChannelID (I only have the UserID and ChannelID).

I would think my Q belongs in here - as mentioned in the link above: _"provide a simple way to allow users to send messages to your web service without having to go through the full process of creating bots via the Microsoft Bot Framework. Outgoing webhooks post data from Teams to any chosen service capable of accepting a JSON payload. Once an outgoing webhook is added to a team, it acts like bot, listening in channels for messages using @mention, sending notifications to external web services, and responding with rich messages that can include cards and images."_

... but I'll be happy to repost this in the Teams repo as well?

Thanks in advance

**Comment by clearab** [comment]
Hi - This question is going to be best answered by the Teams group (since it sounds like you're trying to not use a bot for the interaction). I've ported it to their repository here: https://github.com/MicrosoftDocs/msteams-docs/issues/2550. Please follow that thread, and we can continue the discussion there.

**Comment by dviry** [comment]
Thanks, much appreciated!

Stay safe.
