### ISSUE TITLE
The endpoint property was not recognized as valid HTTPS URL

### ISSUE THREAD

**Issue by HBuddy** [microsoft/botframework-sdk#6188]
![HRBuddyError](https://user-images.githubusercontent.com/78580284/106990001-62317e00-6799-11eb-88a4-d91c26205122.PNG)

i am new to the Microsoft Bot frame work . Im using BOTKIT to develop a chatbot and followed the docs provided in the BOTKIT website . I tried to integrate my code with Teams so i created a bot . I have hosted my bot locally and tried  to added the endpoint in the Bot .I got "http://localhost:3000/api/messages" as my localhost by default , But im getting an error as "The endpoint property was not recognized as valid HTTPS URL" . Can someone help me in resolving the error .

**Comment by v-kydela** [comment]
Thank you for the question, @HBuddy 

You cannot use a localhost endpoint for server-side bot configurations because Teams and Bot Framework services cannot send messages to your client machine. To fix this, you need to get a remote endpoint that forwards requests to your local endpoint through a special application that you run on your machine. This is called a tunneling service. One such tunneling service is called ngrok, and you can learn how to use it here: https://docs.microsoft.com/azure/bot-service/bot-service-debug-channel-ngrok

If you have any more questions, please ask them on Stack Overflow and my team will help you there.
