### ISSUE TITLE
WaterfallStepContext.Values Dictionary changing types between calls

### ISSUE THREAD

**Issue by rslavey** [microsoft/botframework-sdk#6192]
## Version
What package version of the SDK are you using.
4.11.1

## Describe the bug

I have a waterfall step dialog. In the first step I assign the following value:

    stepContext.Values.Add("size", 0);

If I add a GetType on the immediate next line like:

    var tsc = stepContext.Values["size"].GetType();

The value is

    {Name = "Int32" FullName = "System.Int32"}

So far so good. However, on the next step, attempting to cast this value to (int) fails because for some reason it is now an int64:

    var tsc = stepContext.Values["size"].GetType();

Gives me:

    {Name = "Int64" FullName = "System.Int64"}

## To Reproduce
1. Create waterfall dialog
2. Set a value to 0 in one step
3. Attempt to retrieve that value in another step
4. The property is now an int64

## Expected behavior
If I assign an int32 to an object type Dictionary value, I expect an int32 to be returned.

## Screenshots

![image](https://user-images.githubusercontent.com/21177142/107102046-75af0a00-67d6-11eb-8580-b80e6512a140.png)

![image](https://user-images.githubusercontent.com/21177142/107102082-92e3d880-67d6-11eb-89f3-5a51623086ac.png)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by v-kydela** [comment]
Thank you for the report, @rslavey

This is likely because your bot state gets stored as JSON and the Cosmos SDK deserializes integers as long integers. This was reported as a problem multiple times and was fixed in a few places in the SDK:

- https://github.com/Microsoft/botbuilder-dotnet/issues/871
- https://github.com/Microsoft/botbuilder-dotnet/issues/1859

You can fix it in your bot the same way by using `Convert.ToInt32`, or alternatively you can just keep it as a long integer.

To make sure this is actually your issue, please answer the following questions:

1. Are you using Cosmos DB for your dialog state?
2. Is the next waterfall step executed on a different turn from the first step?

**Comment by rslavey** [comment]
Yes and yes. Thanks for the feedback.
