### ISSUE TITLE
Teams Outbound Webhook payload contains incorrect teamsTeamID value

### ISSUE THREAD

**Issue by maircc** [microsoft/botframework-sdk#6243]
Outbound WebHook created in Microsoft Teams.

The payload received at the other end contains an incorrect teamsTeamID in the channelData section.

In excerpt below, see how teamsChannelId and teamsTeamID contain the exact same value. I need to receive the actual group/Team ID so I can call graph queries.       ...Teams/TeamID/ChannelID

The names suggest that this value should contain the actual team ID and it would make sense if it did.

      "channelData": {
            "teamsChannelId": "19:0cb92682ac98403384a7d2e1d2fbac14@thread.tacv2",
            "teamsTeamId": "19:a9e637d882c349aa9a9ebf38b44087d5@thread.tacv2",
            "channel": {
                "id": "19:0cb92682ac98403384a7d2e1d2fbac14@thread.tacv2"
            },
            "team": {
                "id": "19:a9e637d882c349aa9a9ebf38b44087d5@thread.tacv2"
            },
            "tenant": {
                "id": "xxxxxxxxxxxxxxxxxxxxxx"
            }
        },

**Comment by msomanathan** [comment]
@maircc we are working on a major release, so apologies for the delay in getting to this issue. We will respond back with a resolution as soon as we can.

**Comment by peterinnesmsft** [comment]
Hi @maircc,

The values of teamsChannelId and teamsTeamId are not the same in the presented snippet above. Side by side:

- teamsChannelId: 19:0cb92682ac98403384a7d2e1d2fbac14@thread.tacv2
- teamsTeamId:      19:a9e637d882c349aa9a9ebf38b44087d5@thread.tacv2

This data is fed to us from Teams and is not something we have control over. However, there doesn't look to be anything out of place here. I suggest referring to the Teams documentation for further information.

Since it doesn't appear that there is anything actionable here for us, I'm closing this issue out. Let us know if you run into any further issues.
