### ISSUE TITLE
Issue while querying Logs from Application Insights

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/botframework-sdk#6298]
Hi Team,

**Explanation:**
For storing customer user data into Application Insights, we have added the following setup in **Startup.cs**

```c#
public void ConfigureServices(IServiceCollection services)
{ 
        services.AddSingleton<IBotFrameworkHttpAdapter, AdapterWithErrorHandler>();
        services.AddApplicationInsightsTelemetry();
        services.AddSingleton<IBotTelemetryClient, BotTelemetryClient>();
        services.AddSingleton<ITelemetryInitializer, OperationCorrelationTelemetryInitializer>();
        services.AddSingleton<ITelemetryInitializer, TelemetryBotIdInitializer>();
        services.AddSingleton<TelemetryInitializerMiddleware>();
        services.AddSingleton<TelemetryLoggerMiddleware>();
}
// add the below line of code if you want to log personal information as well
services.AddSingleton<TelemetryLoggerMiddleware>(s=>new TelemetryLoggerMiddleware(s.GetService<IBotTelemetryClient>(), true));
```

The above lines of code storing data inside dynamic column of **"CustomDimensions"** inside **"CustomEvents"** table of AppInsights. When the user perform any activity the data is getting stored inside **"CustomDimensions"** column as a json field called **"Activity Id"**. 

**Issue/Problem:**
The problem here is the field **"Activity Id"** inside **"CustomDimensions"** is chaging for every user bot activity interaction.
Details: While inserting every user activity id the field name is dynamically chaging like "Activity Id", "ActivityId", "activityid", "ActivityId" etc. This is not only for **"ActivityId"** but for many columns inside **"CustomDimensions"**.

We have used PowerBI Template to get the Application Insights data as shown in below screenshot but, We are not getting any data for the columns  **"ActivityId"**,  **"ConversationId"** etc as the column names are changing multiple times.
![image](https://user-images.githubusercontent.com/76558423/119618338-68b73480-be20-11eb-98c1-7c6ee579a7d8.png)

Is there any standard solution for this kind of Problem to fetch the data without lost while querying.

**Comment by v-kydela** [comment]
Thank you for the question, @LakshummaC 

This does sound like a problem. Would you be satisfied with a solution that just accounts for all possible name variations in the query, or perhaps one that modifies your existing data so that the fields have the correct name? Or are you asking us to make sure our system writes the field names consistently?

**Comment by LakshummaC** [comment]
For Now, is it possible to change the Power BI templates queries which contains all the possible column name and give us all data without any loss.
and also is it possible to change the existing data that is stored in the application insights so that we have consistent coulmn name for all records.

 

and Finally, can we make sure that bot framework write the field name consistent for future chatbot implementation.
Because we are creating multiple chatbots for different client.

We are using below power bi templates given by microsoft.
https://microsoft.github.io/botframework-solutions/assets/analytics/virtual-assistant-analytics-sample.pbit

**Comment by v-kydela** [comment]
@LakshummaC - Can you provide an example of some of your data that shows the inconsistent field names? Is there any pattern that indicates which situations the different field names get written in? Is it possible that the names just changed over time so that old entries have different names from newer entries, or do you still see a mixture in your most recent data?

Also, I'm trying to figure out who might be a good person to help with this issue. Can you link to the place where you found that Power BI template file? Was it on a GitHub page?

**Comment by LakshummaC** [comment]
@v-kydela Actually because of the NDA i can't share the data here. 
There is no pattern, its just coming randomly for different fields.
New Entries also have same issue with randomly different column name.

https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/

This is the link where i found out power bi template.

**Comment by v-kydela** [comment]
@LakshummaC - Can you provide repro steps so that we can try reproducing the problem on our end?

**Comment by v-kydela** [comment]
@LakshummaC - Are you still working on this?

**Comment by LakshummaC** [comment]
Hi @v-kydela you can create any chatbot like with some dialogs and waterfall steps. Add **direct line** and a **landing html page**. Add the above lines of code (mentioned first in this chat) to store user information to application insights and publish to Azure. Test the bot multiple times through direct line channel and then you can see the number of records missed in power BI template as the field names changing.

**Comment by v-kydela** [comment]
@LakshummaC - Can you reproduce the problem when running the bot locally (i.e. without publishing to Azure)?

**Comment by LakshummaC** [comment]
@v-kydela I didn't try it locally, I see after hosting to azure and in direct line channel

**Comment by v-kydela** [comment]
@LakshummaC - It's always a good idea to try testing a bot locally for debugging purposes. You might find this document helpful: https://docs.microsoft.com/azure/bot-service/bot-service-debug-channel-ngrok

**Comment by v-kydela** [comment]
@LakshummaC - Did you try reproducing the problem with a local bot yet?

**Comment by LakshummaC** [comment]
@v-kydela yes I am done that part as well and its showing the same issue using ngrok

**Comment by v-kydela** [comment]
@LakshummaC - Excellent, thank you for confirming that. So far, I'm unable to reproduce the problem, because all of the properties in the custom dimensions have consistent names between activities. Can you please provide repro steps that can help us generate telemetry with inconsistent field names on our end?

**Comment by LakshummaC** [comment]
@v-kydela Its just same step as like registering direct line channel, used token instead of channel and then chat with chatbot

**Comment by v-kydela** [comment]
@LakshummaC - Are you saying I should be able to send any two activities to a bot in Web Chat and then check App Insights and see different field names in the telemetry for those two activities?

**Comment by LakshummaC** [comment]
@v-kydela Absolutely

**Comment by v-kydela** [comment]
@LakshummaC - Let's say you have a brand new bot without any telemetry yet. What steps would you take to generate telemetry that demonstrates the problem you're talking about?

**Comment by LakshummaC** [comment]
@v-kydela Instead of Webchat try on Directline channel and also its not like every time you will get different column name. You need to try couple of conversationId.

**Comment by v-kydela** [comment]
@LakshummaC - All right well I still can't reproduce the issue so I need to ask some more questions.

1. What documentation have you followed to add telemetry to your bot?
2. Did you enable custom telemetry just by adding code to Startup.cs or did you also put your app insights key in your configuration file?
3. Since you mention Direct Line, are you using Web Chat or a custom Direct Line client?
4. Can you share a minimal example of a Direct Line client that reproduces this problem?
5. Can you share a minimal example of a bot that reproduces this problem?
6. In order to determine if Power BI has anything to do with this, can you see the same inconsistent field names when you view the telemetry in Application Insights directly (outside of Power BI)?
7. Are you able to reproduce the problem in a channel other than Direct Line?

**Comment by v-kydela** [comment]
@LakshummaC - Do you still need help?
