### ISSUE TITLE
HeroCard with Action of type ImBack allows Turn to accept multiple blank submissions from the user after the chosen value is sent

### ISSUE THREAD

**Issue by alinealfa** [microsoft/botframework-sdk#6319]
## Version
botbuilder-ai-4.13.0 
botbuilder-core-4.13.0
botbuilder-dialogs-4.13.0
botbuilder-integration-aiohttp-4.13.0
botframework-connector-4.13.0

## Describe the bug
HeroCard with Action of type ImBack allows Turn to accept multiple blank submissions from the user after the chosen value is sent. This behavior occurs both on the specific web app we've built for the chat and also using the Bot Framework Emulator.
In fact the blank submissions are converted to the last value sent to the Bot, generating multiple responses from the Bot.

It is possible to reproduce the behavior with botbuilder samples which use these components, for instance:
https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/15.handling-attachments

## To Reproduce
1. Start a Bot that uses HeroCard with ActionType ImBack. (for instance, [python sample 15.handling-attachments](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/15.handling-attachments))
2. Interact with the Bot using the Bot Framework Emulator or any other interface.
3. When the HeroCard is shown, click on any option and then press `<enter>` multiple times.
4. The multiple `<enter>` submissions will be converted to the last value sent and the Bot will treat each one as a new command.

## Expected behavior
As it happens with other interaction components of the SDK, blank `<enter>` submissions should not be accepted and handled by the Turn, nor be converted to the last value sent.

## Screenshots
![image](https://user-images.githubusercontent.com/4013036/122215324-612cfd80-ceab-11eb-96d6-89bda7878c97.png)

## Additional context
N/A

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by stevkan** [comment]
@alinealfa, the reason this occurs is because the focus is remaining on the card's button that was originally clicked. If you click into the send box, then the issue doesn't present itself. To that end, this functionality and how to mitigate it, if possible, is going to be client specific. In Web Chat, it can be avoided by disabling any buttons after they have been clicked. It is also possible to reset the focus to the send box on each activity. For 3rd party clients, you would need to research what, if any, options exist to handle this, should it present itself.

I'm going to tag this as a feature request for the Emulator team and let them triage / prioritize.

**Comment by stevkan** [comment]
HI @alinealfa, I have an updated response. While the above holds true with regards to possibly handling the adaptive card functionality, the behavior you are experiencing is actually by design. The basic idea is if there is a card with multiple input fields and/or buttons to be pressed, the focus stays on the card so the user is able to complete whatever other action might be necessary. In this way, the user doesn't have to keep clicking back to the card to continue but can, instead, simply tab thru the card options.

If you feel the default behavior can be improved upon, my recommendation is to create an issue in the [Adaptive Cards](https://github.com/microsoft/AdaptiveCards/issues/new/choose) repo with your feature request / design change for consideration by their team.

**Comment by alinealfa** [comment]
Hi @stevkan, thanks for the update. 
- If there is a response from the bot generating new visible activity items after a button is clicked, my expectation was that the focus would not be kept on the previous button submitted (sometimes the button might not even be visible on the screen; only visible after scrolling up). If the behavior is by design, there might be other cases that it makes sense though. 
- The scenario described is for HeroCard. Is there any specific reason to create an issue in the Adaptive Card repo?
