### ISSUE TITLE
AdaptiveCard with “mailto” Action.OpenUrl is not working for buttons with Image set as well

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-sdk#6326]
## Version
Bot Framework SDK 4.8.1

## Describe the bug
On Microsoft Teams, we are using a customized who bot scenario where we are sending data from Graph API in the adaptive card about the person whom the user is looking for in our bot. The adaptive card contains two icons one chat icon and one mail icon. The chat icon will open a particular person's chat in teams and the mail icon will redirect to outlook with the particular user's email id in the To column. At present on clicking the mail icon is again redirecting back in teams in Web and is not working in the desktop client. Please help me how to redirect it properly to Outlook when the mail icon is clicked.

## Screenshots
Please find the screenshots below:

![image](https://user-images.githubusercontent.com/51920866/122531376-0d521e00-d03d-11eb-9b4d-aab3686ac111.png)

**Comment by v-kydela** [comment]
Thank you for the report, @RajdeepRay0411. I'm going to close this because the problem is on the Teams side and it's not a Bot Framework bug or feature request.

You can send feedback to Teams through the Teams app directly or you can report bugs in the [Teams docs repo](https://github.com/MicrosoftDocs/msteams-docs/issues). If you have a how-to question then you can use the [`microsoft-teams`](https://stackoverflow.com/questions/tagged/microsoft-teams) tag on Stack Overflow.
