### ISSUE TITLE
LUIS and QnA maker dispatcher is slow

### ISSUE THREAD

**Issue by astuj** [microsoft/botframework-sdk#6339]
## Version
SDK Language: .Net
SDK Version: 4.14.0
Development Environment: localhost and Azure

## Describe the bug
I am trying to create a bot that uses both the LUIS and a QnA maker, to implement that I have use the dispatcher CLI as suggested in the docs. My issue is that the bot is taking a long time to reply to the user and I do understand that as it goes to dispatcher created LUIS model first and then depending on the intent it again fetches from one of the LUIS/QnA model the actual answer to the asked question. Is there any workaround to make the whole process a little faster? 

I was going through LUIS and I noticed that we can export the LUIS model as a JSON, I was just wondering if we can create a LUIS recogniser using that JSON in the project itself saving us the calls and could potentially make the whole process smoother.

Any leads will be appreciated, thanks.

**Comment by hcyang** [comment]
Hi @astuj,

By default, the Dispatch CLI is in the hierarchical mode that would require invoking the 2-call mechanism as you mentioned, unless the sub-apps are all LUIS.
You can disable that using the  "--hierarchical" option (https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch), then all the intents in LUIS and QnA-Maker answers would be "flattened" in the Dispatch LUIS app, instead of just two intents for the two sub-apps. In this flattened setting, your bot would only need to make one call to the Dispatch LUIS app and the predictions would be directly to the LUIS sub-app intents and QnA Maker answers. 

Nevertheless, we are deprecating the C# LUIS Dispatch CLI and replacing it with a Transformer-based Orchestrator CLI (https://github.com/microsoft/botframework-cli). Here are some example links for the Orchestrator-based dispatch scenario with LUIS and QnaMaker as sub-apps: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/14.nlp-with-orchestrator and https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/14.nlp-with-orchestrator.
Orchestrator is inherently a local on-premise app, so once your bot receives the dispatch prediction, it can either call LUIS or QnA Maker services. You can also train Orchestrator models using the sub-app (LUIS and QnA Maker) utterance set as well. In that case, all the predictions (dispatch and intent/QnA) are local, not service is involved.
