### ISSUE TITLE
Orchestrator Documentation Enhancements

### ISSUE THREAD

**Issue by DKdekes** [microsoft/botframework-sdk#6424]
## Issue

I cannot find any in depth documentation on Orchestrator's snapshot files.

## Proposed change

Add answers to the following questions to Orchestrator docs:

- What is the purpose of the snapshot file? Is it to avoid forward propagating all training utterances through the Orchestrator’s transformer at startup?
 
- What is the encoded data contained in the snapshot? Is it transformer output vectors?
 
- Are snapshot files created using newer versions of Orchestrator backwards compatible with older versions of orchestrator runtime? If so, will this always be true?
 
- Why do snapshot files contain raw utterance data?

## Customer Impact

Improved understanding of how snapshots can fit into a ModelOps strategy.

**Comment by daveta** [comment]
Hi @DKdekes:
The snapshot is an opaque format that stores the "model" or definition of your utterances.  This helps with performance as it pre-calculates each utterance to avoid additional processing during runtime.  But to your point, yes, it's fundamentally storing vectors.  And it doesn't require storing raw utterance data.

**Comment by hcyang** [comment]
Hi @DKdekes,

We haven't changed the snapshot file format since GA (general availability), so Orchestrator is backward compatible to snapshot files generated since GA.
A snapshot file can be used as a source for bf-cli to mix with other sources and generate a "dispatch" snapshot. For that Orchestrator utilizes the utterances and labels in a snapshot source. 

May I ask what's your reason for not wanting utterances in a snapshot file output?

If you are sure a snapshot is final and you will use it for and only for prediction purpose, then for privacy concern, you can use a JSON or plain editor (either a program or manual) to anonymize the utterances before sharing it. 
However, the utterances won't be shown in a prediction result for the "closest_text" attribute and for explainability purpose -- to explain how Orchestrator makes a prediction by showing a semantically similar utterance from the snapshot.

For privacy issue, bf-cli's "test" command has a hidden, undocumented parameter to obfuscate labels and utterances during creating evaluation reports. You can set the "obfuscate" environment variable before you run the "test" command to achieve that. However the reports may not be easy to comprehensive, well, as the labels and utterances are all obfuscated.

**Comment by DKdekes** [comment]
Thanks for the replies.

> May I ask what's your reason for not wanting utterances in a snapshot file output?

@hcyang, I was thinking raw utterance data would be used as training data if there was a model version mismatch between Orchestrator runtime and the CLI that generated the snapshot. I'm assuming that each model documented in [NLRModels.md](https://github.com/microsoft/botframework-sdk/blob/main/Orchestrator/docs/NLRModels.md) produces a different vector for a given utterance, so a snapshot created using one model cannot be imported into a runtime using another model. Is this assumption accurate?

**Comment by hcyang** [comment]
@DKdekes, what you surmised is true. The snapshot file also captures model ids for the embeddings created. Orchestrator throws an error if the model id encoded in the snapshot file is not the same with the model loaded for prediction.

**Comment by tsuwandy** [comment]
@DKdekes, do you have other questions on Orchestrator orchestrator?

**Comment by DKdekes** [comment]
Not at this time. Thanks for the information.
