### ISSUE TITLE
Whether can we share same cosmos db table for master bot and skill bots?

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-sdk#6482]
i have 3 skill bots and a master bot, Is it possible to share the same cosmos db table for orchestrator bot and skill bots?

**Comment by dmvtech** [comment]
Hi @amoyalan20 As this is more of a question/How-to, this is better addressed on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). 

> i have 3 skill bots and a master bot, Is it possible to share the same cosmos db table for orchestrator bot and skill bots?

To clarify; you mean the same 'container', correct? I believe so. As each will have different conversation IDs at the very least. It also depends on if you want to have different partition keys or not. You could have each using a different partition key (although I'm not sure how much you might have to change in the code/SDK to make that happen).

**Comment by amoyalan20** [comment]
Hi @dmvtech, Thanks for your response.
we are currently working with cosmos db table api. so, can we try to implement the above solution with the same db or is there any limitation or issue with the cosmos db table api to achieve the result?

**Comment by dmvtech** [comment]
@amoyalan20 

What are you using the cosmos api for? Are you using it for something related to the bot conversation/user state? Or is it not related to the underlining bot framework, but another aspect of what you are trying to in your application/bot? 

It depends on the needs of what you are actually trying to implement. If you're wanting to handle bot state, then **do not** use the API and use the built in `CosmosDbPartitionedStorage` storage class (instead of [MemoryStorage](https://github.com/microsoft/BotBuilder-Samples/blob/67dc482eafc1e1f52c97a3018c7370cba8c21868/samples/csharp_dotnetcore/03.welcome-user/Startup.cs#L28)). If you're not using it to deal with bot state, you can certainly use a single database, as long as it meets the needs of whatever you are trying to accomplish.

**Comment by dmvtech** [comment]
Closing assuming that you have the needed info. If you have further questions; please ask them on Stack Overflow with clarifying specifics.
