### ISSUE TITLE
POST to Bot timed out after 15s

### ISSUE THREAD

**Issue by samthrusha123** [microsoft/botframework-sdk#6535]
Sometimes I am getting timeout error from my bot.
Is there any option to increase that 15 seconds time?

Please let me know if you need any other information

**Comment by ramfattah** [comment]
Hi @samthrusha123 

The 15 second timeout is a Direct Line service timeout. This is by design, NOT a bug.

Some guidance for performing long operations within a bot can be found in this doc: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance

If you require further assistance, please direct questions to Stack Overflow using the #botframework tag.
