### ISSUE TITLE
On Microsoft teams when I click allow permission to download file. I got something went wrong message

### ISSUE THREAD

**Issue by ChernHwee** [microsoft/botframework-sdk#6559]
## Describe the bug
On Microsoft teams application. After I followed and ran [56.teams-file-upload](https://github.com/microsoft/BotBuilder-Samples/tree/22fcff680a3e11006eb09b81ac5ed4de345933e2/archive/samples/python/56.teams-file-upload), I have click allowed  and it shows the something went wrong message

## To Reproduce
1. Execute 56.teams-file-upload example
2. type something on the bot
3. Press allow in the upload permission

## Expected behavior
Upon clicking it, it should not show the something went wrong

## Screenshots
![image](https://user-images.githubusercontent.com/72246152/207523122-9fe831c0-8b00-4e81-be67-9a08d6cd4aaa.png)

**Comment by anishprasad01** [comment]
Hi @ChernHwee,

I am able to reproduce this. However, it also appears that no errors occurred within the bot and the Teams logo image was successfully uploaded to OneDrive. 

Given that, it seems likely that this issue is occurring on the Teams client side. The [Teams samples repo](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/368ef561bad496948b30ac0c23b38ad207adf891/samples/bot-file-upload/python) actually owns this now as well, and I would request you open an issue with them to see if they can advise as to why the error message is popping up incorrectly.
