### ISSUE TITLE
The Link to the C# Orchestrator sample does not exist

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/botframework-sdk#6568]
The C# sample for the bot framework SDK documentation is not found.

## Version
v4

**Comment by anishprasad01** [comment]
Hi @aishwaryaumachandran,

These samples are archived due to the deprecation of QnA Maker and the forthcoming deprecation of LUIS. If you have an existing implementation and need access to the samples, you can find them in the [archived samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/archive) for the time being.

As the documentation states, for **new** bots, look into using the [orchestration workflow](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs#:~:text=For%20new%20bots%2C%20consider%20using%20the%20question%20answering%20and%20orchestration%20workflow%20features%20of%20Azure%20Cognitive%20Service%20for%20Language.) of the new Azure Cognitive Service for Language resources.
