### ISSUE TITLE
Remove app from personal scope

### ISSUE THREAD

**Issue by jnaglis** [microsoft/botframework-sdk#6604]
## Describe the bug
When app is removed from personal scope OnTeamsMembersRemovedAsync is not called.
In some cases has been observed that also OnInstallationUpdateAddAsync and OnTeamsMembersAddedAsync called after removing app from personal scope.

## To Reproduce
1. Install app to personal scope by uploading manifest
2. Remove app from personal scope

## Expected behavior
OnMembersRemovedAsync called after app removed from personal scope. And not OnInstallationUpdateAddAsync and OnTeamsMembersAddedAsync.

**Comment by ramfattah** [comment]
Thanks @jnaglis, I'm looking into this.

**Comment by ramfattah** [comment]
Hi @jnaglis, 

are you removing the app in Teams application or Teams Admin Center portal?

**Comment by jnaglis** [comment]
Hi @ramfattah,
In Teams application.

**Comment by ramfattah** [comment]
Hi @jnaglis, 

For uninstallation in the personal scope, the "Install update event" is triggered, aligning with the official Teams documentation. It appears this behavior is by design. 

Please refer to the [Uninstall behavior for personal app with bot](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#install-update-event) for more details.

Example: 
```cs
protected override async Task OnInstallationUpdateActivityAsync(ITurnContext<IInstallationUpdateActivity> turnContext, CancellationToken cancellationToken)
{
    var activity = turnContext.Activity;
    if (string.Equals(activity.Action, "Add", StringComparison.InvariantCultureIgnoreCase))
    {
        // TO:DO Installation workflow.
    }
    else
    {
        // TO:DO Uninstallation workflow.
    }
    return;
}
```
